# Generated by Django 4.1 on 2022-11-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'servico', 'verbose_name_plural': 'serviços'},
        ),
        migrations.RemoveField(
            model_name='servico',
            name='protocole',
        ),
        migrations.AddField(
            model_name='servico',
            name='protocolo',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar válcula do motor'), ('TO', 'Troca de óleo'), ('B', 'Balanceamento')], max_length=3, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_entrega',
            field=models.DateField(null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_inicio',
            field=models.DateField(null=True, verbose_name='Data de ínicio'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
    ]
