# Generated by Django 4.1 on 2023-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_options_remove_servico_protocole_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'serviço', 'verbose_name_plural': 'serviços'},
        ),
        migrations.AddField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
