# Generated by Django 4.1 on 2022-11-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_carro_placa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ('lavagens', 'consertos', 'ano'), 'verbose_name': 'carro', 'verbose_name_plural': 'carros'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nome', 'sobrenome'), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='carro',
            field=models.CharField(max_length=50, verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='consertos',
            field=models.IntegerField(default=0, verbose_name='Consertos'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='lavagens',
            field=models.IntegerField(default=0, verbose_name='Lavagens'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=7, unique=True, verbose_name='Placa'),
        ),
    ]
